# Generated by Django 3.2 on 2024-08-15 17:04

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='tsv_description',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='tsv_title',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
