# Generated by Django 3.2 on 2024-08-15 17:06

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20240815_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='tsv_description',
        ),
        migrations.RemoveField(
            model_name='author',
            name='tsv_title',
        ),
        migrations.AddField(
            model_name='book',
            name='tsv_description',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tsv_title',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
