# Generated by Django 3.2 on 2024-08-15 18:16

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20240815_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsv_description'], name='idx_tsv_description_gin'),
        ),
    ]
