# Generated by Django 3.2 on 2024-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20240815_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='embedding',
            field=models.JSONField(null=True),
        ),
    ]
