# Generated by Django 3.2 on 2024-08-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_book_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
